In [1]:
import numpy as np


## DataTypes & Attributes

In [2]:
#Numpy main data type is ndarray
a1 = np.array([1,2,3,4])
a1

array([1, 2, 3, 4])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1,2,3,4],
               [5,6,7,8]])
a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
a3 = np.array([[[12,3,4],
               [22,4,5],
               [2,4,5]],
              [[1,2,3],
              [4,5,6],
              [34,6,7]]])
a3

array([[[12,  3,  4],
        [22,  4,  5],
        [ 2,  4,  5]],

       [[ 1,  2,  3],
        [ 4,  5,  6],
        [34,  6,  7]]])

In [17]:
a1.shape

(4,)

In [18]:
a2.shape

(2, 4)

In [19]:
a3.shape

(2, 3, 3)

In [20]:
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [21]:
a4 = a1*a2

In [22]:
a4

array([[ 1,  4,  9, 16],
       [ 5, 12, 21, 32]])

In [23]:
a1.dtype,a2.dtype,a2.dtype

(dtype('int32'), dtype('int32'), dtype('int32'))

In [24]:
a1.size,a2.size,a3.size

(4, 8, 18)

In [25]:
type(a1),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [27]:
import pandas as pd
df = pd.DataFrame(a2)

In [28]:
df

0  1  2  3
0  1  2  3  4
1  5  6  7  8

## Creating Arrays


In [2]:
import numpy as np
sample_array = np.array([2,34,5,6])
sample_array

array([ 2, 34,  5,  6])

In [3]:
sample_array.dtype

dtype('int32')

In [4]:
once = np.ones((2,3))

In [5]:
once

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
once.dtype

dtype('float64')

In [7]:
zeroes = np.zeros((2,3))

In [8]:
zeroes

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [15]:
random_array = np.random.randint(0,10, size = (3,3)) 
random_array

array([[5, 2, 3],
       [5, 5, 9],
       [9, 1, 8]])

In [16]:
random_array.size

9

In [17]:
random_array.shape

(3, 3)

In [18]:
random_array.imag

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [19]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.96235727, 0.4861599 , 0.87512142],
       [0.46512885, 0.38443609, 0.9138499 ],
       [0.23230801, 0.67870083, 0.19709602],
       [0.33389182, 0.10000083, 0.28579868],
       [0.27401963, 0.85728957, 0.03063312]])

In [20]:
random_array_3 = np.random.randint(2,10,size = (3,4))
random_array_3

array([[4, 9, 9, 2],
       [4, 5, 6, 7],
       [6, 2, 7, 9]])

In [36]:
random_array_4 = np.random.random((4,4,3))
random_array_4
a = np.random.random(3)
a

array([0.27962281, 0.58129321, 0.82023929])

In [43]:
random_array_5 = np.random.choice(a)
random_array_5

0.5812932115773887

In [57]:
np.random.seed(6)
random_array_6 = np.random.randint(10,size = (3,4))
random_array_6

array([[9, 3, 4, 0],
       [9, 1, 9, 1],
       [4, 1, 8, 2]])

In [56]:
random_array_6 = np.random.randint(10,size = (3,4))
random_array_6

array([[4, 2, 5, 9],
       [6, 2, 5, 5],
       [1, 4, 5, 0]])